### ISSUE TITLE
Code not working: ModuleNotFoundError: No module named 'agents'

### ISSUE THREAD

**Issue by Youjin1985** [javyduck/ChatScene#15]
~/ChatScene-main$ PYTHONPATH='./' python scripts/run_train.py --agent_cfg=adv_scenic.yaml --scenario_cfg=train_scenario_scenic.yaml --mode train_scenario --scenario_id 1
setGPU: Setting GPU to: 0
pygame 2.3.0 (SDL 2.24.2, Python 3.8.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "scripts/run_train.py", line 18, in <module>
    from safebench.carla_runner import CarlaRunner
  File "/home/genesis/ChatScene-main/safebench/carla_runner.py", line 20, in <module>
    from safebench.gym_carla.envs.render import BirdeyeRender
  File "/home/genesis/ChatScene-main/safebench/gym_carla/envs/__init__.py", line 11, in <module>
    from safebench.gym_carla.envs.carla_env import CarlaEnv
  File "/home/genesis/ChatScene-main/safebench/gym_carla/envs/carla_env.py", line 31, in <module>
    from safebench.scenario.scenario_definition.route_scenario import RouteScenario
  File "/home/genesis/ChatScene-main/safebench/scenario/__init__.py", line 16, in <module>
    from safebench.scenario.scenario_policy.adv_patch import ObjectDetection
  File "/home/genesis/ChatScene-main/safebench/scenario/scenario_policy/adv_patch.py", line 21, in <module>
    from safebench.agent.object_detection.utils.general import cv2
  File "/home/genesis/ChatScene-main/safebench/agent/__init__.py", line 17, in <module>
    from safebench.agent.basic import CarlaBasicAgent
  File "/home/genesis/ChatScene-main/safebench/agent/basic.py", line 14, in <module>
    from agents.navigation.basic_agent import BasicAgent  
ModuleNotFoundError: No module named 'agents'

can you please test code before putting into production?

**Comment by Youjin1985** [comment]
sorry didn't pay attention to PYTHONPATH
