### ISSUE TITLE
train_scenari

### ISSUE THREAD

**Issue by AndyBestaa** [javyduck/ChatScene#20]
python 3.9.0
When I ran the command
`python scripts/run_train.py --agent_cfg=adv_scenic.yaml --scenario_cfg=train_scenario_scenic.yaml --mode train_scenario --scenario_id 1`
An error occurred.
`setGPU: Setting GPU to: 0
pygame 2.6.1 (SDL 2.28.4, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-10-27 18:46:29.624515: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "D:\Wsz\paper\Zhang_ChatScene_Knowledge-Enabled_Safety-Critical_Scenario_Generation_for_Autonomous_Vehicles_CVPR_2024_paper\ChatScene\scripts\run_train.py", line 32, in <module>
    from safebench.carla_runner import CarlaRunner
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\carla_runner.py", line 20, in <module>
    from safebench.gym_carla.envs.render import BirdeyeRender
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\gym_carla\envs\__init__.py", line 11, in <module>
    from safebench.gym_carla.envs.carla_env import CarlaEnv
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\gym_carla\envs\carla_env.py", line 31, in <module>
    from safebench.scenario.scenario_definition.route_scenario import RouteScenario
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\scenario\__init__.py", line 16, in <module>
    from safebench.scenario.scenario_policy.adv_patch import ObjectDetection
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\scenario\scenario_policy\adv_patch.py", line 21, in <module>
    from safebench.agent.object_detection.utils.general import cv2
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\agent\__init__.py", line 17, in <module>
    from safebench.agent.basic import CarlaBasicAgent
  File "d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene\safebench\agent\basic.py", line 14, in <module>
    from agents.navigation.basic_agent import BasicAgent
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\agents\__init__.py", line 21, in <module>
    from . import algorithms
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\agents\algorithms\__init__.py", line 21, in <module>
    from .ppo import PPO
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\agents\algorithms\ppo\__init__.py", line 21, in <module>
    from .ppo import PPO
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\agents\algorithms\ppo\ppo.py", line 27, in <module>
    import tensorflow as tf
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 5906, in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 433, in Optional
    return Union[arg, type(None)]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\86135\AppData\Local\Programs\Python\Python39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'`
I want to know if it is due to the incompatibility of library versions?Or other reasons?
`Package                      Version      Editable project location
---------------------------- ------------ -------------------------------------------------------------------------------------------------------------------------------------------
absl-py                      2.1.0
agents                       1.4.0
ansicon                      1.89.0
antlr4-python3-runtime       4.13.2
asttokens                    2.4.1
astunparse                   1.6.3
attrs                        24.2.0
blessed                      1.20.0
blinker                      1.8.2
cachetools                   5.5.0
carla                        0.9.15
certifi                      2024.8.30
charset-normalizer           3.4.0
click                        8.1.7
cloudpickle                  3.1.0
colorama                     0.4.6
comm                         0.2.2
ConfigArgParse               1.7
contourpy                    1.3.0
cycler                       0.12.1
dash                         2.18.1
dash-core-components         2.0.0
dash-html-components         2.0.0
dash-table                   5.0.0
decorator                    5.1.1
dotmap                       1.3.30
exceptiongroup               1.2.2
executing                    2.1.0
fastjsonschema               2.20.0
filelock                     3.13.1
Flask                        3.0.3
flatbuffers                  24.3.25
fonttools                    4.54.1
fsspec                       2024.2.0
future                       1.0.0
gast                         0.4.0
google-auth                  2.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
gpustat                      1.1.1
grpcio                       1.67.0
gym                          0.26.2
gym-notices                  0.0.8
h5py                         3.12.1
idna                         3.10
imageio                      2.36.0
imageio-ffmpeg               0.5.1
importlib_metadata           8.5.0
importlib_resources          6.4.5
ipython                      8.18.1
ipywidgets                   8.1.5
itsdangerous                 2.2.0
jedi                         0.19.1
Jinja2                       3.1.4
jinxed                       1.3.0
jsonschema                   4.23.0
jsonschema-specifications    2024.10.1
jupyter_core                 5.7.2
jupyterlab_widgets           3.0.13
keras                        3.6.0
kiwisolver                   1.4.7
lazy_loader                  0.4
libclang                     18.1.1
mapbox_earcut                1.0.2
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   3.0.2
matplotlib                   3.9.2
matplotlib-inline            0.1.7
mdurl                        0.1.2
ml-dtypes                    0.3.2
moviepy                      1.0.2
mpmath                       1.3.0
namex                        0.0.8
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.2.1
numpy                        1.26.4
nvidia-ml-py                 12.560.30
oauthlib                     3.2.2
open3d                       0.18.0
opencv-python                4.10.0.84
opt_einsum                   3.4.0
optree                       0.13.0
packaging                    24.1
pandas                       2.2.3
parso                        0.8.4
Pillow                       9.5.0
pip                          24.2
platformdirs                 4.3.6
plotly                       5.24.1
proglog                      0.1.10
prompt_toolkit               3.0.48
protobuf                     4.25.5
psutil                       6.1.0
pure_eval                    0.2.3
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pygame                       2.6.1
Pygments                     2.18.0
pyparsing                    3.2.0
python-dateutil              2.9.0.post0
pytz                         2024.2
pywin32                      308
PyYAML                       6.0.2
referencing                  0.35.1
requests                     2.32.3
requests-oauthlib            2.0.0
retrying                     1.3.4
rich                         13.9.3
rpds-py                      0.20.0
rsa                          4.9
ruamel.yaml                  0.18.6
ruamel.yaml.clib             0.2.12
safebench                    1.0.0        d:\wsz\paper\zhang_chatscene_knowledge-enabled_safety-critical_scenario_generation_for_autonomous_vehicles_cvpr_2024_paper\chatscene
scenic                       2.1.0b4      D:\Wsz\paper\Zhang_ChatScene_Knowledge-Enabled_Safety-Critical_Scenario_Generation_for_Autonomous_Vehicles_CVPR_2024_paper\ChatScene\Scenic
scikit-image                 0.24.0
scipy                        1.13.1
setGPU                       0.0.7
setuptools                   75.2.0
Shapely                      1.8.5.post1
six                          1.16.0
stack-data                   0.6.3
sympy                        1.13.1
tenacity                     9.0.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorboard-plugin-wit       1.8.1
tensorflow                   2.16.1
tensorflow-estimator         2.11.0
tensorflow-intel             2.16.1
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.5.0
tifffile                     2024.8.30
torch                        2.5.0+cu124
torchaudio                   2.5.0+cu124
torchvision                  0.20.0+cu124
tqdm                         4.66.5
traitlets                    5.14.3
typing_extensions            4.12.2
tzdata                       2024.2
urllib3                      2.2.3
wcwidth                      0.2.13
Werkzeug                     3.0.4
wheel                        0.44.0
widgetsnbextension           4.0.13
wrapt                        1.16.0
zipp                         3.20.2`

**Comment by javyduck** [comment]
hi, it is due to the version of python 3.9.0:

In Python 3.9.0, the typing module has a bug that causes a TypeError when certain type annotations are processed. Specifically, annotations involving Optional, Callable, and nested lists can trigger this error.

So the one solution is you can downgrade the python version to 3.8.16, and it should work.

**Comment by AndyBestaa** [comment]
> hi, it is due to the version of python 3.9.0:
> 
> In Python 3.9.0, the typing module has a bug that causes a TypeError when certain type annotations are processed. Specifically, annotations involving Optional, Callable, and nested lists can trigger this error.
> 
> So one solution is you can simply downgrade the python version to 3.8.16, and it should work.

Yes, I succeeded with python3.8.6. Thank you!
However, when I started training, this situation occurred several times.
![image](https://github.com/user-attachments/assets/c83d53d5-a3f9-4f00-b78f-2eaff5940314)

![image](https://github.com/user-attachments/assets/d7ce9986-2f02-4ccb-9be0-f4f9020ca68b)

The version of Carla I am using is 0.9.15. Does this have anything to do with the version?Could you please help me and give me some suggestions?
